language: node_js

sudo: enabled

services:
  - docker

node_js:
  - "8"

before_install:
  - docker pull lavenderflowerdew/alpine-base

install:
  - npm install -g brunch
  - npm install

script: brunch build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_USERNAME/$DOCKER_REPO" .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_USERNAME/$DOCKER_REPO";
    fi
